apiVersion: apps/v1
kind: Deployment
metadata:
  name: trap
spec:
  selector:
    matchLabels:
      app: trap
  replicas: 1 
  template:
    metadata:
      labels:
        app: trap
    spec:
      containers:
      - name: trap
        image: registry.gitlab.com/mehdi-group/trap
      imagePullSecrets:
      - name: gitlab-credentials
